# Generated by Django 5.0.4 on 2024-05-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_employee_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
