# Generated by Django 5.0.4 on 2024-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_employee_address_alter_employee_adhar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='adhar',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Adhar Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emg_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Emergency Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='epf',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='EPF UAN Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esic',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ESIC ID'),
        ),
    ]
