# Generated by Django 5.0.4 on 2024-05-08 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_employee_assigned_to_employee_wrk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'designation__name__in': ['Project Manager', 'Project Coordinator', 'System Administrator', 'Office Administrator']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
