# Generated by Django 5.0.4 on 2024-05-08 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_employee_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='test_field',
        ),
        migrations.AlterField(
            model_name='employee',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Manager'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
