# Generated by Django 5.0.4 on 2024-05-09 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_employee_test_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='booked_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Manager'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_booked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
