# Generated by Django 5.0.4 on 2024-05-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='start_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
