# Generated by Django 5.0.4 on 2024-05-13 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_holiday_end_date_alter_holiday_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Full Day'), (2, 'First Half'), (3, 'Second Half'), (4, 'Fullday with Second Half of Start Date'), (5, 'Fullday with First Half of End Date')], max_length=1)),
                ('start_date', models.DateTimeField(unique=True)),
                ('end_date', models.DateTimeField()),
                ('reasone', models.CharField(max_length=500)),
                ('manager_status', models.BooleanField(default=False)),
                ('hr_status', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
