# Generated by Django 5.0.4 on 2024-05-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('1', 'Full Day'), ('2', 'First Half'), ('3', 'Second Half'), ('4', 'Fullday with Second Half of Start Date'), ('5', 'Fullday with First Half of End Date')], max_length=1),
        ),
    ]
